import React, { useState } from "react";
import { 
  FileText, 
  Download, 
  Video, 
  Radio, 
  Sparkles, 
  BookOpen, 
  Send, 
  X, 
  CheckCircle,
  Clock,
  Compass,
  ArrowRight
} from "lucide-react";
import { DOWNLOADABLE_RESOURCES } from "../data.js";

export default function MediaResourcesSection() {
  const [selectedDownload, setSelectedDownload] = useState<typeof DOWNLOADABLE_RESOURCES[number] | null>(null);
  const [optInEmail, setOptInEmail] = useState("");
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  const handleOptInSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!optInEmail.trim()) return;

    setDownloadSuccess(true);
    setTimeout(() => {
      // Simulate file download by creating an invisible anchor
      const mockBlob = new Blob([`Visual Resource: ${selectedDownload?.title || 'Guides'}. Generated by PiusOwolawi.com`], { type: "text/plain" });
      const url = URL.createObjectURL(mockBlob);
      const link = document.createElement("a");
      link.href = url;
      link.download = selectedDownload ? `${selectedDownload.id}_guide_preview.txt` : "pius_owolawi_framework.txt";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      // Clean state
      setDownloadSuccess(false);
      setSelectedDownload(null);
      setOptInEmail("");
    }, 2000);
  };

  return (
    <div id="media-resources-section" className="space-y-16 animate-in fade-in duration-300 font-sans">
      
      {/* 1. Resources Intro Header */}
      <div className="space-y-3">
        <span className="font-mono text-xs font-bold text-[#C9A84C] uppercase tracking-widest block">CURATED BROADCASTS & COMPILATIONS</span>
        <h2 className="font-sans text-3xl font-extrabold tracking-tight text-white">Media Appearances & Resources</h2>
        <p className="font-sans text-sm text-gray-300 max-w-2xl leading-relaxed">
          Access Prof. Owolawi's media files, 4IR policy reports, lecture broadcasts, and downloadable technical guidelines designed specifically for engineers, university deans, and postgraduate researchers.
        </p>
      </div>

      {/* 2. CURATED DOWNLOADABLE PDFS (With opt-in gating) */}
      <div className="space-y-6">
        <div className="space-y-1">
          <h3 className="font-sans text-xl font-bold text-white flex items-center gap-2">
            <span className="h-1.5 w-1.5 bg-[#C9A84C] rounded-full" />
            Downloadable Guides & Frameworks
          </h3>
          <p className="text-xs text-[#7A8898]">Secure opt-in required to request administrative PDF access keys</p>
        </div>

        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
          {DOWNLOADABLE_RESOURCES.map((r) => (
            <div 
              key={r.id}
              className="rounded-xl border border-[#2E3A4A]/25 bg-[#0E1623] p-5 shadow-sm hover:border-[#C9A84C]/50 transition-all flex flex-col justify-between group"
            >
              <div className="space-y-3">
                <div className="rounded-lg bg-[#C9A84C]/10 p-2.5 text-[#C9A84C] w-max">
                  <FileText className="h-5 w-5" />
                </div>
                <div>
                  <span className="font-mono text-[9px] text-[#C9A84C] uppercase block tracking-wider font-semibold">{r.pages} Pages • {r.format}</span>
                  <h4 className="font-sans text-sm font-bold text-white group-hover:text-[#C9A84C] transition-colors leading-snug mt-1">{r.title}</h4>
                </div>
                <p className="text-xs text-slate-500 leading-relaxed font-sans">{r.description}</p>
              </div>

              <button
                onClick={() => setSelectedDownload(r)}
                className="w-full rounded bg-[#C9A84C]/10 border border-[#C9A84C]/35 px-4 py-2 text-xs font-mono font-bold text-[#C9A84C] hover:bg-[#C9A84C] hover:text-[#0A1628] transition-all text-center flex items-center justify-center gap-1.5 mt-5"
              >
                <Download className="h-3.5 w-3.5" />
                Download Resource
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* 3. Media Coverage / Press & Appearances Calendar */}
      <div className="space-y-6">
        <div className="space-y-1">
          <h3 className="font-sans text-xl font-bold text-white flex items-center gap-1.5">
            <Radio className="text-[#C9A84C] h-5 w-5" />
            Press Mentions & Audio Interviews
          </h3>
          <p className="text-xs text-[#7A8898]">Key technical analyses delivered on public-interest television, regional radio, and print panels</p>
        </div>

        <div className="grid gap-6 md:grid-cols-3">
          
          {/* Item 1 */}
          <div className="rounded-xl border border-[#2E3A4A]/25 bg-[#0E1623]/60 p-5 space-y-3">
            <div className="flex justify-between items-start font-mono text-[10px]">
              <span className="text-amber-500 font-bold bg-amber-500/10 border border-amber-500/35 px-2 py-0.5 rounded uppercase flex items-center gap-1">
                <Video className="h-3 w-3" /> TV Feature
              </span>
              <span className="text-gray-500">2024</span>
            </div>
            <h4 className="font-sans text-base font-bold text-white leading-snug">4IR Skills Gap in Sub-Saharan Banking Sector</h4>
            <p className="text-xs text-gray-350 leading-relaxed font-sans">Delivered a 10-minute technical evaluation on SABC News assessing automation displacement risks for regional vocational graduates.</p>
            <span className="text-[10px] text-gray-500 block font-mono">Platform: SABC News Channel 404</span>
          </div>

          {/* Item 2 */}
          <div className="rounded-xl border border-[#2E3A4A]/25 bg-[#0E1623]/60 p-5 space-y-3">
            <div className="flex justify-between items-start font-mono text-[10px]">
              <span className="text-[#C9A84C] font-bold bg-[#C9A84C]/10 border border-[#C9A84C]/35 px-2 py-0.5 rounded uppercase flex items-center gap-1">
                <Radio className="h-3 w-3" /> Radio Panel
              </span>
              <span className="text-gray-500">2023</span>
            </div>
            <h4 className="font-sans text-base font-bold text-white leading-snug">Agricultural Drones & Aviation Policy Scopes</h4>
            <p className="text-xs text-gray-350 leading-relaxed font-sans">Radio presentation on SAFM analyzing SACAA licensing pipelines for commercial UAV sprays across Limpopo crop zones.</p>
            <span className="text-[10px] text-gray-500 block font-mono">Platform: SAFM National Broadcast</span>
          </div>

          {/* Item 3 */}
          <div className="rounded-xl border border-[#2E3A4A]/25 bg-[#0E1623]/60 p-5 space-y-3">
            <div className="flex justify-between items-start font-mono text-[10px]">
              <span className="text-blue-400 font-bold bg-blue-500/10 border border-blue-500/25 px-2 py-0.5 rounded uppercase flex items-center gap-1">
                <FileText className="h-3 w-3" /> Column / Press
              </span>
              <span className="text-gray-500">2022</span>
            </div>
            <h4 className="font-sans text-base font-bold text-white leading-snug">Bridging Low-Resource Digital Classroom Models</h4>
            <p className="text-xs text-gray-350 leading-relaxed font-sans">In-depth printed interview analyzing video compressed caching mechanisms inside remote Soshanguve school classrooms.</p>
            <span className="text-[10px] text-gray-500 block font-mono">Platform: TechCentral South Africa</span>
          </div>

        </div>
      </div>

      {/* 4. OPT-IN GATEWAY POPUP FORM MODAL */}
      {selectedDownload && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 px-4 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="relative w-full max-w-md rounded-2xl border border-[#2E3A4A] bg-[#0E1E34] p-6 text-white shadow-2xl animate-in scale-in duration-150">
            <button 
              onClick={() => setSelectedDownload(null)}
              className="absolute right-4 top-4 text-gray-400 hover:text-white"
            >
              <X className="h-5 w-5" />
            </button>

            {downloadSuccess ? (
              <div className="py-8 text-center space-y-3 font-sans">
                <div className="mx-auto h-12 w-12 rounded-full bg-emerald-500/10 flex items-center justify-center border border-emerald-500 text-emerald-500">
                  <CheckCircle className="h-6 w-6" />
                </div>
                <h3 className="text-lg font-bold text-white">Resource Unlocked</h3>
                <p className="text-xs text-gray-450 max-w-sm mx-auto">
                  Opt-in verified! An active preview download for <strong>{selectedDownload.title}</strong> has been initialized successfully. Enjoy exploring his frameworks.
                </p>
              </div>
            ) : (
              <form onSubmit={handleOptInSubmit} className="space-y-4 font-sans">
                <div className="border-b border-[#2E3A4A] pb-2.5">
                  <span className="font-mono text-[9px] text-[#C9A84C] uppercase tracking-wider block font-medium">Download Gateway Request</span>
                  <h3 className="text-base font-bold text-white">Unlock: {selectedDownload.title}</h3>
                  <p className="text-xs text-gray-450 mt-0.5">Please provide a valid work or academic email to download this framework preview.</p>
                </div>

                <div className="space-y-3.5 text-xs">
                  <div className="space-y-1">
                    <label className="text-gray-400">Institutional Email Address *</label>
                    <input 
                      type="email" 
                      required
                      value={optInEmail}
                      onChange={(e) => setOptInEmail(e.target.value)}
                      className="w-full rounded border border-[#2E3A4A] bg-[#07111D] px-3.5 py-2.5 text-white focus:outline-none focus:border-[#C9A84C]"
                      placeholder="e.g. yourname@university.edu"
                    />
                  </div>

                  <div className="flex gap-2.5 text-[11px] text-gray-400 leading-snug">
                    <input type="checkbox" required defaultChecked className="mt-0.5 rounded bg-black border border-gray-600 cursor-pointer" />
                    <span>I opt-in to receive academic research correspondence, post-graduate study vacancy announcements, and digital policy circulars directly from Prof. Owolawi's office.</span>
                  </div>
                </div>

                <div className="flex justify-end gap-2 pt-2 text-xs">
                  <button 
                    type="button" 
                    onClick={() => setSelectedDownload(null)}
                    className="rounded border border-gray-600 bg-transparent px-4 py-2 hover:bg-gray-800"
                  >
                    Cancel
                  </button>
                  <button 
                    type="submit" 
                    className="rounded bg-[#C9A84C] text-[#0A1628] font-bold px-5 py-2 hover:bg-[#C9A84C]/90 flex items-center gap-1.5"
                  >
                    <Send className="h-3.5 w-3.5" />
                    Download PDF Preview
                  </button>
                </div>
              </form>
            )}
          </div>
        </div>
      )}

    </div>
  );
}
